name: WordPress Tests

on:
    pull_request:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, intl, pdo_sqlite, sqlite3
                  tools: composer, wp
            - name: Install Dependencies
              run: composer install
            - name: Install WordPress
              run: |
                  mkdir -p tests/_wordpress
                  wp core download --allow-root --version=6.7 --path=tests/_wordpress
            - name: Run Tests
              run: vendor/bin/codecept run
