name: WordPress Tests

on:
    pull_request:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        outputs:
            status: ${{ steps.check.outputs.conclusion }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Fetch base branch for comparison
              run: git fetch origin ${{ github.base_ref }}
            - name: Check for relevant changes
              id: check
              env:
                  FILES_TO_CHECK: 'includes/** autoblue.php uninstall.php'
              run: |
                  changed_files=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} -- $FILES_TO_CHECK)
                  if [ -z "$changed_files" ]; then
                    echo "conclusion=should-run" >> $GITHUB_OUTPUT
                  else
                    echo "conclusion=should-not-run" >> $GITHUB_OUTPUT
                  fi
    tests:
        runs-on: ubuntu-latest
        needs: check
        if: needs.check.outputs.status == 'should-run'
        steps:
            - uses: actions/checkout@v3
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, intl, pdo_sqlite, sqlite3
                  tools: composer, wp
            - name: Get Composer cache directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-
            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress
            - name: Cache WordPress
              id: cache-wordpress
              uses: actions/cache@v4
              with:
                  path: tests/_wordpress
                  key: wordpress-6.7
            - name: Install WordPress
              if: steps.cache-wordpress.outputs.cache-hit != 'true'
              run: |
                  mkdir -p tests/_wordpress
                  wp core download --allow-root --version=6.7 --path=tests/_wordpress
            - name: PHPCS
              run: vendor/bin/phpcs .
            - name: PHPStan
              run: vendor/bin/phpstan
            - name: Run Tests
              run: vendor/bin/codecept run
